----------------------------Create departments table
-- CREATE TABLE department (
-- dept_no VARCHAR PRIMARY KEY,
-- 	dept_name VARCHAR(60)
-- );
----------------------------------------------------
----------------------------Create titles table
-- CREATE TABLE titles (
-- title_id VARCHAR PRIMARY KEY,
-- 	title VARCHAR(60)
-- );
----------------------------------------------------
----------------------------Create employees table
-- CREATE TABLE employees (
-- emp_no INTEGER PRIMARY KEY,
-- 	emp_title_id VARCHAR NOT NULL,
-- 	birth_date DATE,
-- 	first_name VARCHAR(40),
-- 	last_name VARCHAR (40),
-- 	sex VARCHAR (3),
-- 	hire_date DATE,
-- 	FOREIGN KEY(emp_title_id) REFERENCES titles(title_id)
-- );
----------------------------------------------------
----------------------------Create dept_manager table
-- CREATE TABLE dept_manager(
-- dept_no VARCHAR,
-- 	emp_no INT,
-- 	FOREIGN KEY(dept_no) REFERENCES department(dept_no),
-- 	FOREIGN KEY(emp_no) REFERENCES employees(emp_no)
-- );
----------------------------------------------------
----------------------------Create dept_emp table
-- CREATE TABLE dept_emp(
-- 	emp_no INT,
-- dept_no VARCHAR,
-- 	FOREIGN KEY(emp_no) REFERENCES employees(emp_no),
-- 	FOREIGN KEY(dept_no) REFERENCES department(dept_no)
-- );
----------------------------------------------------
----------------------------Create salaries table
-- CREATE TABLE salaries(
-- 	emp_no INT,
-- salary INT,
-- 	FOREIGN KEY(emp_no) REFERENCES employees(emp_no)
-- );
----------------------------------------------------